steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:latest',
      '-t', 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:$BUILD_ID',
      '.'
    ]
  
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:$BUILD_ID']

# Store images in Artifact Registry
images:
  - 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:latest'
  - 'europe-west1-docker.pkg.dev/wahrify-fact-checker/wahrify-backend/wahrify-backend:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'