"""add batch post id to claims table

Revision ID: 142219b495ef
Revises: 2abb9260c6fd
Create Date: 2025-04-15 19:00:55.462331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "142219b495ef"
down_revision: Union[str, None] = "2abb9260c6fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claims", sa.Column("batch_post_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("claims", "batch_post_id")
    # ### end Alembic commands ###
