"""update search table

Revision ID: 41ab48ec3620
Revises: 6b09687fcbbd
Create Date: 2025-01-23 20:35:34.475581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41ab48ec3620'
down_revision: Union[str, None] = '6b09687fcbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('DELETE FROM sources')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('analysis_id', sa.UUID(), nullable=False))
    op.add_column('searches', sa.Column('prompt', sa.Text(), nullable=False))
    op.alter_column('searches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('searches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_searches_analysis_id'), 'searches', ['analysis_id'], unique=False)
    op.create_foreign_key(op.f('fk_searches_analysis_id_analysis'), 'searches', 'analysis', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.add_column('sources', sa.Column('search_id', sa.UUID(), nullable=False))
    op.drop_index('ix_sources_analysis_id', table_name='sources')
    op.create_index(op.f('ix_sources_search_id'), 'sources', ['search_id'], unique=False)
    op.drop_constraint('fk_sources_analysis_id_analysis', 'sources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sources_search_id_searches'), 'sources', 'searches', ['search_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sources', 'analysis_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_sources_search_id_searches'), 'sources', type_='foreignkey')
    op.create_foreign_key('fk_sources_analysis_id_analysis', 'sources', 'analysis', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sources_search_id'), table_name='sources')
    op.create_index('ix_sources_analysis_id', 'sources', ['analysis_id'], unique=False)
    op.drop_column('sources', 'search_id')
    op.drop_constraint(op.f('fk_searches_analysis_id_analysis'), 'searches', type_='foreignkey')
    op.drop_index(op.f('ix_searches_analysis_id'), table_name='searches')
    op.alter_column('searches', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('searches', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('searches', 'prompt')
    op.drop_column('searches', 'analysis_id')
    # ### end Alembic commands ###
