"""add summary to search table

Revision ID: 4bd2e2c4bc6c
Revises: 41ab48ec3620
Create Date: 2025-01-25 17:37:05.186593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd2e2c4bc6c'
down_revision: Union[str, None] = '41ab48ec3620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'summary')
    # ### end Alembic commands ###
