"""remove unique sources constraint

Revision ID: b2122b621d0a
Revises: c705bfe3c5ed
Create Date: 2025-03-25 19:05:08.818440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2122b621d0a'
down_revision: Union[str, None] = 'c705bfe3c5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_url_hash', table_name='sources')
    op.create_index('ix_source_url_hash', 'sources', [sa.text('md5(url)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_url_hash', table_name='sources')
    op.create_index('idx_source_url_hash', 'sources', [sa.text('md5(url::text)')], unique=True)
    # ### end Alembic commands ###
